[project]
name = "MinecraftQueqiao"
version = "0.1.0"
description = "我的世界鹊桥连接器"
authors = [
    {name = "sssysy", email = "sssysy@vip.qq.com"},
]
dependencies = ["aio-mc-rcon>=3.4.2", "mcstatus>=11.0.0"]
requires-python = ">=3.12"
readme = "README.md"
license = {file = "LICENSE"}


[tool.pdm]
distribution = false
